### ISSUE TITLE
UnboundLocalError: local variable 'n1' referenced before assignment

### ISSUE THREAD

**Issue by james-skelton** [biomedbigdata/BiCoN#11]
I updated BiCoN to the latest version (via pip) today, and get this error when I run BiCoN on the `pan_cancer_breast.csv` file with an `lg_min` of 5 and an `lg_max` of 25. I can make the gene-gene network file available, if required! 

From a quick look at the code, it seems that `n1` is defined within a few conditional blocks, and so I'd guess the conditions required aren't being met.

```
Runtime statistics:
###############################################################
the joint graph has 2762 nodes
probability update takes 44.746
Iteration # 1
One ant work takes 57.44 with 8 processes
best round score: 0
average score: -1.091
Count small = 1
Traceback (most recent call last):
  File "/home/james/repodb_v1/experimental/fastapi/dev/tools/run_bicon.py", line 69, in <module>
    run()
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/james/repodb_v1/experimental/fastapi/dev/tools/run_bicon.py", line 27, in run
    solution, scores = model.run_search(logging=True, n_proc=8)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/bicon/ants.py", line 252, in run_search
    t0 = self.pher_upd(t0, t_min, evaporation, [n1, n2], solution_big_best)
UnboundLocalError: local variable 'n1' referenced before assignment
```

**Comment by Laolga** [comment]
Hi James,
Could you please provide your gene-gene network?

**Comment by james-skelton** [comment]
Thanks for the response -- network attached.

[gg.tsv.zip](https://github.com/biomedbigdata/BiCoN/files/5637095/gg.tsv.zip)

**Comment by Laolga** [comment]
Hi James,
This issue should be fixed now. Please update the package to the latest version (1.2.9).
Thank you for your feedback and feel free to reopen the issue if something does not look ok.

Olga.

**Comment by james-skelton** [comment]
Hi again,

Thanks for investigating. With the new version, I seem to be getting a new error (with the same inputs) -- trace below.

Cheers,
James

```
Traceback (most recent call last):
  File "/home/james/repodb_v1/experimental/fastapi/dev/tools/run_bicon.py", line 69, in <module>
    run()
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/james/repodb_v1/experimental/fastapi/dev/tools/run_bicon.py", line 27, in run
    solution, scores = model.run_search(logging=True, n_proc=8)
  File "/home/james/miniconda3/envs/bicon/lib/python3.7/site-packages/bicon/ants.py", line 253, in run_search
    t0 = self.pher_upd(t0, t_min, evaporation, [n1, n2], solution_big_best)
UnboundLocalError: local variable 'solution_big_best' referenced before assignment
```

**Comment by Laolga** [comment]
Hi James,
Please update and test again.

Best,
Olga
